{% set name = "pp-sketchlib" %}
{% set version = "2.1.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/bacpop/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: c8bbf8bf98dcc757121397b729c9bda2bc56bee6914d4f5eac85a833b23ae0e2
  patches:
    - 0001-Fix-for-type-of-index-on-llvm-compiler.patch
    - pp-sketchlib-aarch64.patch  # [aarch64]

build:
  number: 0
  skip: true  # [py<38 or win or cuda_compiler_version in ("9.2", "10.0", "10.1", "10.2", "11.0")]
  script_env:
    # Ensure that CUDA includes can be found by the host compiler
    - CUDA_HOME={{ os.sep.join([BUILD_PREFIX, "targets", "x86_64-linux"]) }}  # [linux64 and cuda_compiler_version not in ("None", "11.8")]
    - CUDA_HOME={{ os.sep.join([BUILD_PREFIX, "targets", "sbsa-linux"]) }}    # [linux and aarch64 and cuda_compiler_version not in ("None", "11.8")]
    - CUDA_HOME={{ os.sep.join([BUILD_PREFIX, "targets", "ppc64le-linux"]) }}    # [linux and ppc64le and cuda_compiler_version not in ("None", "11.8")]
    - SKETCHLIB_INSTALL=conda                                                 # [linux and cuda_compiler_version not in ("None", "11.8")]
  script:
    - {{ PYTHON }} -m pip install . -vvv
  missing_dso_whitelist:
    - '*/libcuda.*'
  ignore_run_exports:
    - cudatoolkit
  entry_points:
    - sketchlib = pp_sketch.__main__:main

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux and cuda_compiler_version != "None"]
    - cmake >=3.19
    - make
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - pybind11 >=2.12.0                      # [build_platform != target_platform]
  host:
    - python
    - pip
    - setuptools
    - pybind11
    - highfive
    - zlib
    - eigen
    - hdf5
    - openblas
    - llvm-openmp  # [osx]
    - libgomp      # [linux]
  run:
    - python
    - numpy
    - scipy
    - libblas * *openblas
    - openblas
    - zlib
    - h5py
    - docopt
    - libgfortran           # [linux]
    - gfortran_impl_osx-64  # [osx]

test:
  imports:
    - pp_sketchlib
  commands:
    - sketchlib --version

about:
  home: https://github.com/bacpop/pp-sketchlib
  license: Apache-2.0 AND MIT AND BSD-3-Clause
  license_file:
    - NOTICE
    - LICENSE
    - LICENSE_highfive
    - LICENSE_bindash
    - LICENSE_nthash
    - LICENSE_kseq
    - LICENSE_json.txt
    - LICENSE_KMeansRex
    - LICENSE_unordered_dense
  summary: Library of sketching functions used by PopPUNK
  doc_url: https://poppunk.bacpop.org/
  dev_url: https://github.com/bacpop/pp-sketchlib

extra:
  recipe-maintainers:
    - johnlees
