{% set name = "pp-sketchlib" %}
{% set version = "1.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/johnlees/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 52eb17edcef82a7c8d7fd8a37c88a595e89d116d92bf807bb788364e586326f3

build:
  number: 0
  skip: true  # [py2k or win or cuda_compiler_version in ("9.2", "10.0", "10.1", "10.2")]
  script:
    - export SKETCHLIB_INSTALL=conda  # [linux64 and cuda_compiler_version != "None"]
    - {{ PYTHON }} -m pip install . --no-deps -vv
  missing_dso_whitelist:
    - '*/libcuda.*'
  ignore_run_exports:
    - cudatoolkit
    - armadillo
  entry_points:
    - poppunk_sketch = pp_sketch.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    - cmake >=3.19
  host:
    - python
    - pip
    - pybind11
    - highfive
    - zlib
    - eigen
    - armadillo
    - hdf5
    - openblas
    - llvm-openmp  # [osx]
    - libgomp      # [linux64]
  run:
    - python
    - numpy
    - scipy
    - libblas * *openblas
    - openblas
    - zlib
    - h5py
    - libgfortran-ng        # [linux64]
    - gfortran_impl_osx-64  # [osx]

test:
  imports:
    - pp_sketch
  commands:
    - poppunk_sketch --version

about:
  home: https://github.com/johnlees/pp-sketchlib
  license: Apache-2.0 AND MIT
  license_file:
    - NOTICE
    - LICENSE
    - LICENSE_bindash
    - LICENSE_nthash
    - LICENSE_kseq
    - LICENSE_json.txt
  summary: Library of sketching functions used by PopPUNK
  doc_url: https://www.poppunk.net
  dev_url: https://github.com/johnlees/pp-sketchlib

extra:
  recipe-maintainers:
    - johnlees
