{% set name = "pp-sketchlib" %}
{% set version = "1.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/johnlees/{{ name|lower }}/archive/v{{ version }}.tar.gz
  sha256: 1a5c192259264b532e4fe8415e92608fcb4eb92e080b04e7defa4f52a9aa64f8
  patches:
    - 0001-Use-makefile-in-setup.py.patch  # [linux64 and cuda_compiler_version != "None"]
    - 0002-Make-rng-constexpr-for-clang.patch  # [osx]

build:
  number: 0
  skip: true  # [py2k or win or cuda_compiler_version == '9.2']
  script:
    - {{ PYTHON }} -m pip install . --no-deps -vv
  missing_dso_whitelist:
    - '*/libcuda.*'
  ignore_run_exports:
    - cudatoolkit
    - armadillo
  entry_points:
    - poppunk_sketch = pp_sketch.__main__:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ compiler('cuda') }}  # [linux64 and cuda_compiler_version != "None"]
    - cmake
  host:
    - python
    - pip
    - pybind11
    - highfive
    - zlib
    - eigen
    - armadillo
    - hdf5
    - openblas
    - openmp
  run:
    - python
    - numpy
    - scipy
    - libblas * *openblas
    - openblas
    - zlib
    - h5py
    - libgfortran-ng  # [linux64]
    - gfortran_impl_osx-64  # [osx]

test:
  imports:
    - pp_sketch
  commands:
    - poppunk_sketch --version

about:
  home: https://github.com/johnlees/pp-sketchlib
  license: Apache-2.0 AND MIT
  license_file:
    - NOTICE
    - LICENSE
    - LICENSE_bindash
    - LICENSE_nthash
    - LICENSE_kseq
  summary: Library of sketching functions used by PopPUNK
  doc_url: https://www.poppunk.net
  dev_url: https://github.com/johnlees/pp-sketchlib

extra:
  recipe-maintainers:
    - johnlees
